liato/android-bankdroid

- app/src/main/java/com/liato/bankdroid/banking/banks/coop/Coop.java
Coop have introduced some new cards the MedMera-Mer is one of them (I don't have the other cards so I can't add support for more than this atm).
https://www.coop.se/Betalkort-och-bank/Vara-betal--och-kreditkort/
The patch is verified and works fine.
> added support for Coop's MedMera-Mer MasterCard

- app/src/main/java/com/liato/bankdroid/banking/banks/nordea/Nordea.java
I wrongly assumed the currency column would hold the currency information for credit cards with other native currencies.
It turns out it holds the native amount and currency of the /transaction/, when it's not in SEK. This fix fetches the account currency from the table header instead.
> Fixed faulty credit card currency parsing

- app/src/main/java/com/liato/bankdroid/banking/banks/coop/Coop.java
Various updates for the Coop credit cards.
> Added support for point balance at Coop

- app/src/main/java/eu/nullbyte/android/urllib/CertPinningSSLSocketFactory.java
> Fixes support for old servers and removes SSLv3.

- app/src/main/java/com/liato/bankdroid/banking/banks/SvenskaSpel.java
> Changed API for Svenska Spel. Fixes #376

- app/src/main/java/com/liato/bankdroid/banking/banks/avanza/Avanza.java
added support to show balance. Also, shows all sub-accounts as main accounts.
> Avanza patch

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Jojo.java
Makes it possible to get all your registered cards.
Fixes #383
> Use personal account for Jojo Reskassa.

- app/src/main/java/com/liato/bankdroid/TransactionsActivity.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/Transaction.java
> Sort transactions in descending order.

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Volvofinans.java
> Add Locale.UK for date parser to be able to parse the CET time zone.

- app/src/main/java/com/liato/bankdroid/ActivityHelper.java
- app/src/main/java/com/liato/bankdroid/BankEditActivity.java
- app/src/main/java/com/liato/bankdroid/DataRetrieverTask.java
Check if activity is finishing before dismissing dialog from background tasks.
Fixes #424
> Check if activity is finishing before dismissing dialog

- app/src/main/java/com/liato/bankdroid/liveview/LiveViewService.java
> Updates icon name for SonyMobile LiveView menu icon.

- app/src/main/java/com/liato/bankdroid/MainActivity.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/Bank.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/swedbank/AbstractSwedbank.java
Adds feature to disable the www button if a bank does not support www login.
Disable www button for Swedbank and Sparbankerna.
> Adds feature to disable the www button

- .gitignore
- app/build.gradle
- app/crashlytics.properties.example
- app/proguard-rules.pro
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/liato/bankdroid/BankEditActivity.java
- app/src/main/java/com/liato/bankdroid/BankdroidApplication.java
- app/src/main/java/com/liato/bankdroid/DataRetrieverTask.java
- app/src/main/java/com/liato/bankdroid/appwidget/AutoRefreshService.java
- app/src/main/java/com/liato/bankdroid/appwidget/BankdroidWidgetProvider.java
> Adds Crashlytics crash reporting.

- app/build.gradle
> Makes crashlytics optional.

- app/src/main/AndroidManifest.xml
> Fixes crash if dialog is shown when screen is rotated.

- app/src/main/res/layout-land/confirm_lock_pattern.xml
- app/src/main/res/layout/confirm_lock_pattern.xml
> Replace @*android references.

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/swedbank/AbstractSwedbank.java
> Use LoginException if user tries to use Swedbank with a Sparbanken account

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/ForexBank.java
Fixed problem with transactions for one of the accounts showing for all accounts.
> Fixed transactions for Forex, fixes #257

- app/src/main/java/com/liato/bankdroid/MainActivity.java
- app/src/main/java/com/liato/bankdroid/appwidget/AutoRefreshService.java
- app/src/main/java/com/liato/bankdroid/banking/BankFactory.java
- app/src/main/java/com/liato/bankdroid/db/DBAdapter.java
- app/src/main/java/com/liato/bankdroid/db/DatabaseHelper.java
- app/src/main/java/com/liato/bankdroid/provider/BankTransactionsProvider.java
To prevent database locking.
See http://touchlabblog.tumblr.com/post/24474750219/single-sqlite-connection
Fixes #189
> Use a single database connection for the whole application.

- bankdroid-legacy/src/main/java/eu/nullbyte/android/urllib/Urllib.java
> Adds null check before calling toString on HttpEntity

- app/src/main/java/com/liato/bankdroid/BankEditActivity.java
> Check if activity is finishing before alert dialog is shown.

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Villabanken.java
> Check that regex matches before adding account for Villabanken.

- app/src/main/java/com/liato/bankdroid/BankdroidApplication.java
- app/src/main/java/com/liato/bankdroid/MainActivity.java
- app/src/main/java/com/liato/bankdroid/TransactionsActivity.java
- app/src/main/java/com/liato/bankdroid/banking/BankFactory.java
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values/strings.xml
> Verify that both the bank and account exists before showing its transactions

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Nordnet.java
Fixes issues with Nordnet, fixes #104
> Fixes issues with Nordnet, fixes #104

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankFactory.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/swedbank/SparbankernaCorporate.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/swedbank/SparbankernaYouth.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/swedbank/Swedbank.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/swedbank/SwedbankCorporate.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/swedbank/SwedbankYouth.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/provider/IBankTypes.java
Needs to be verified by actual users because I have neither a youth or a corporate account available to test with.
Fixes #316
> Adds support for Swedbank and Sparbankerna Youth and Corporate profiles.

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankFactory.java
> Disable Skandiabanken due to requirement of BankId.

- config/quality/quality.gradle
Now findbugs will scan all sub modules and not only the app module.
> Fixes findbugs scan issue.

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/TicketRikskortet.java
> Remove catching of IOException for Rikskortet

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Jojo.java
> Adds support for paginated list of Jojo cards.

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Bredband2VoIP.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Chalmrest.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/avanza/Avanza.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/coop/Coop.java
catching `Exception` should be avoided for bank classes and handled by the caller.
> Fixes IOException handling.

- CHANGELOG
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankFactory.java
> Removes Sparbanken Öresund due to BankId requirement.

- CHANGELOG
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Jojo.java
> Adds null check for pagination existens.

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/lansforsakringar/Lansforsakringar.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/swedbank/AbstractSwedbank.java
Replaces catching of `Exception` with more specific exceptions. And do not handle `IOException`.
> Improves Exception handling

- app/src/main/java/com/liato/bankdroid/db/DBAdapter.java
- app/src/main/java/com/liato/bankdroid/db/DatabaseHelper.java
- app/src/main/java/com/liato/bankdroid/db/LegacyDatabase.java
This is the first PR in a series where the goal is to implement custom properties and prepare for the next major release. 
This PR does not change any functionality.
> Refactor database creation

- CHANGELOG
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/TicketRikskortet.java
Ticket Rikskortet is currently broken because URLs have changed. Fix this
> Adapt to new URLs for Ticket Rikskortet

- CHANGELOG
- app/proguard-rules.pro
> Fixes NoClassDefFoundException for Samsung devices running 4.2

- app/src/main/java/com/liato/bankdroid/banking/BankFactory.java
- app/src/main/java/com/liato/bankdroid/db/DBAdapter.java
- app/src/main/java/com/liato/bankdroid/db/Database.java
- app/src/main/java/com/liato/bankdroid/db/DatabaseHelper.java
- app/src/main/java/com/liato/bankdroid/db/LegacyDatabase.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/Bank.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyProviderConfiguration.java
Moves username, password and extras fields to the new properties table.
Adds properties map to Bank class.
Initial implementation for #334
> Initial support for custom properties.

- app/src/main/java/com/liato/bankdroid/BankEditActivity.java
- app/src/main/java/com/liato/bankdroid/banking/BankFactory.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/Bank.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankFactory.java
Removed some unused code.
Improved implementation of selecting bank in spinner.
> Code improvements

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/AmericanExpress.java
Amex cards bug out when you pay the invoice. Not only does bankdroid fail to parse that, it assigns the text of "BETALNING MOTTAGEN, TACK" to the closest other transaction, meaning that transaction text dissappears.
This patch will properly parse both columns of values, and correctly detect if it's an invoice payment or other kinds of refund.
> Fix AmEx parsing for incoming payments

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Chalmrest.java
Adapt to new site for "Chalmers Konferens & Restauranger" (Chalmrest).
> Adapt to new site for Chalmrest

- CHANGELOG
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankFactory.java
(Swedbank, Sparbankerna, Marginalen and NordeaDK)
Closes #566.
> Deactivated banks requiring BankId 

- CHANGELOG
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankFactory.java
> Removes support for Forex Bank

- CHANGELOG
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/MinPension.java
The first url have changed, this fixes that.
> Fix for login issues with "Min Pension.se"

- .travis.yml
- CHANGELOG
- app/build.gradle
- app/src/main/java/com/liato/bankdroid/appwidget/AutoRefreshService.java
- app/src/main/res/values/themes.xml
- bankdroid-legacy/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Attempt to add support for Android-M, to fix #582 .
> Added support for Android 6.0 Marshmallow

- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/OKQ8.java
OKQ8 has made some minor changes to their website.
> Fixes for OKQ8, fixes #597

- CHANGELOG
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/Bank.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/lansforsakringar/Lansforsakringar.java
Also comment some previously undocumented parts of the Bank class.
Have tried Länsförsäkringar with this change applied and it still works
like a charm.
Fixes #609.
> Remove the broken web-bank links from LF

- app/src/main/java/com/liato/bankdroid/DataRetrieverTask.java
- app/src/main/java/com/liato/bankdroid/lockpattern/LockPatternUtils.java
- app/src/main/java/net/margaritov/preference/colorpicker/AlphaPatternDrawable.java
- app/src/main/java/net/margaritov/preference/colorpicker/ColorPickerView.java
- app/src/main/java/net/sf/andhsli/hotspotlogin/SimpleCrypto.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/OKQ8.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Osuuspankki.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/PayPal.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Zidisha.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/avanza/Avanza.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/ica/ICA.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/icabanken/ICABanken.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/lansforsakringar/Lansforsakringar.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/seb/model/UserCredentials.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/swedbank/AbstractSwedbank.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/utils/Installation.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/utils/StringUtils.java
- bankdroid-legacy/src/main/java/eu/nullbyte/android/urllib/Urllib.java
- config/quality/quality.gradle
And remedy those left; they weren't that many to begin with.
I like FindBugs; it finds bugs. And I prefer it finding them to me
finding them.
> Fail build on FindBugs violations

- CHANGELOG
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankFactory.java
Since they now require MobiltBankID.
Fixes #619
> Removes support for IcaBanken

- app/src/main/java/com/liato/bankdroid/appwidget/AutoRefreshService.java
- app/src/main/java/com/liato/bankdroid/appwidget/BankdroidWidgetProvider.java
- app/src/main/java/com/liato/bankdroid/liveview/LiveViewService.java
- app/src/main/java/com/liato/bankdroid/lockpattern/ChooseLockPattern.java
- app/src/main/java/com/liato/bankdroid/lockpattern/ChooseLockPatternExample.java
- app/src/main/java/com/liato/bankdroid/lockpattern/ConfirmLockPattern.java
- config/quality/pmd/pmd-ruleset.xml
- config/quality/quality.gradle
Since fixing everything at once isn't really possible I just removed
all the rules, put in a much shorter list and fixed that.
If more rules are deemed important, there are instructions in
pmd-ruleset.xml on how to do that.
> Enforce PMD rules on "./gradlew check"

- app/build.gradle
- app/src/main/java/com/liato/bankdroid/provider/BankTransactionsProvider.java
- config/quality/lint/lint.xml
- config/quality/quality.gradle
Fix one issue, disable lots of warnings to enable merging *something*
at least.
> Fail build on Android Lint problems

- config/quality/lint/lint.xml
- create-lint-suppressions.sh
And provide a script to find out what could actually be enabled.
> Re-enable lots of lint checks

- config/quality/pmd/pmd-ruleset.xml
- config/quality/quality.gradle
- create-pmd-suppressions.sh
And add a script for updating the list.
Note that I haven't actually fixed anything in here, and there are some
kind-of-scary-looking suppressions (like "EmptyIfStmt").
Fixing those would be another exercise though, the only point of this
change is really to document what we're violating and make sure nobody
adds to that list.
> Enable all non-violated PMD rules

- .travis.yml
- app/build.gradle
- app/src/main/java/com/liato/bankdroid/BetterPopupWindow.java
- app/src/main/java/com/liato/bankdroid/DataRetrieverTask.java
- app/src/main/java/com/liato/bankdroid/MainActivity.java
- app/src/main/java/com/liato/bankdroid/WebViewActivity.java
- app/src/main/java/net/margaritov/preference/colorpicker/ColorPickerDialog.java
- app/src/main/java/net/margaritov/preference/colorpicker/ColorPickerPreference.java
- bankdroid-legacy/build.gradle
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/Bank.java
- build.gradle
- config/quality/lint/lint.xml
- config/quality/pmd/pmd-ruleset.xml
This change fixes Instant Run in Android Studio 2.2.1 by upgrading the
Android Build Tools Gradle dependency (as suggested by Android Studio)
and by not storing Contexts in static variables (as suggested by
Android Lint).
> Fix Instant Run

- app/src/main/java/com/liato/bankdroid/MainActivity.java
- app/src/main/java/net/margaritov/preference/colorpicker/ColorPickerDialog.java
An earlier PR by myself is the source of these crashes. But at least I
found them myself :/.
All three popups are now tested and working.
> Fix crashing popup windows

- app/build.gradle
- bankdroid-legacy/build.gradle
- build.gradle
- config/quality/lint/lint.xml
- tools/update-suppressions.sh
Upgrades the following dependencies to the latest stable:
`com.android.support:appcompat-v7`
`com.android.tools.build:gradle`
> Upgrade gradle build tools to latest stable.

- app/src/main/java/com/liato/bankdroid/TimePreference.java
- app/src/main/java/com/liato/bankdroid/appwidget/AutoRefreshService.java
- app/src/main/java/com/liato/bankdroid/appwidget/BankdroidWidgetProvider.java
- app/src/main/java/com/liato/bankdroid/banking/BankFactory.java
- app/src/main/java/net/margaritov/preference/colorpicker/ColorPickerPreference.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/Helpers.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankHelper.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Jojo.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/lansforsakringar/Lansforsakringar.java
- bankdroid-legacy/src/main/java/eu/nullbyte/android/urllib/CertPinningSSLSocketFactory.java
- bankdroid-legacy/src/main/java/eu/nullbyte/android/urllib/CertificateReader.java
- bankdroid-legacy/src/main/java/eu/nullbyte/android/urllib/Urllib.java
- config/quality/pmd/pmd-ruleset.xml
This should improve the Crashlytics statistics.
> Fix empty catch blocks

- app/build.gradle
- app/src/main/java/com/liato/bankdroid/BankEditActivity.java
- app/src/main/java/com/liato/bankdroid/db/DBAdapter.java
- app/src/main/java/com/liato/bankdroid/db/DatabaseHelper.java
- bankdroid-interface/src/main/java/com/liato/bankdroid/api/configuration/Entry.java
- bankdroid-interface/src/main/java/com/liato/bankdroid/api/configuration/FieldBuilder.java
- bankdroid-interface/src/main/java/com/liato/bankdroid/api/domain/account/impl/AbstractAccountBuilder.java
- bankdroid-interface/src/main/java/com/liato/bankdroid/api/domain/account/impl/AccountBuilder.java
- bankdroid-interface/src/main/java/com/liato/bankdroid/api/domain/account/impl/CreditCardAccountBuilder.java
- bankdroid-interface/src/main/java/com/liato/bankdroid/api/domain/account/impl/EquityAccountBuilder.java
- bankdroid-interface/src/main/java/com/liato/bankdroid/api/domain/account/impl/EquityBuilder.java
- bankdroid-interface/src/main/java/com/liato/bankdroid/api/domain/account/impl/LiabilityAccountBuilder.java
- bankdroid-interface/src/main/java/com/liato/bankdroid/api/domain/account/impl/PrePaidCardAccountBuilder.java
- bankdroid-interface/src/main/java/com/liato/bankdroid/api/domain/account/impl/TransactionAccountBuilder.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/Bank.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankHelper.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/OKQ8.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/SveaDirekt.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/americanexpress/AmericanExpress.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/americanexpress/model/Card.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/americanexpress/model/LoginResponse.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/americanexpress/model/TransactionDetails.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/lansforsakringar/Lansforsakringar.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/rikslunchen/Rikslunchen.java
- bankdroid-legacy/src/main/java/com/liato/bankdroid/utils/FieldTypeMapper.java
- config/quality/checkstyle/checkstyle.xml
- config/quality/quality.gradle
Enable Checkstyle whitespace checks.
Ran into some violations in an earlier PR, found it was bad for readability.
> Fix whitespace issues

- .travis.yml
- app/build.gradle
- app/src/main/java/com/liato/bankdroid/MainActivity.java
- bankdroid-interface/src/main/java/com/liato/bankdroid/api/configuration/FieldBuilder.java
- bankdroid-legacy/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
gradle 3.3
com.android.tools.build:gradle:2.3.0
buildToolsVersion 25.0.1
sdkVersion 25
> Upgrade android build tools
