app/src/main/java/com/liato/bankdroid/TransactionsActivity.java
This have been bugging me for so long, not being able to go back by clicking on the account name to go back when viewing transactions.
=> Support to go back to main view from transaction view

tools/print_expired_certificates
I created a simple script to check for expired certificates. It runs on linux so depending on your development environment it may or it may not work.
It found some aging certificates so hopefully it's of some use:
```
cert_americanexpress_global.pem: Feb 8 23:59:59 2015 GMT
cert_bioklubben.pem: Aug 29 23:59:59 2014 GMT
cert_everydaycard.pem: Jun 1 23:59:59 2012 GMT
cert_mobilbanken.pem: Nov 7 23:59:59 2014 GMT
cert_osuuspankki.pem: Dec 12 23:59:59 2014 GMT
cert_osuuspankki_mobile.pem: Sep 13 23:59:59 2014 GMT
cert_plusgirot.pem: Jan 23 23:59:59 2015 GMT
cert_seb_web.pem: Jul 22 23:59:59 2014 GMT
```
=> Add basic shell script which prints expired certificates

bankdroid-legacy/build.gradle
Fixes build error for `bankdroid-legacy` module
=> Do not abort build on lint errors.

bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankFactory.java
Removes the following banks because they requires SMS or BankId to login.
* Handelsbanken
* SEB
* Chevrolet
* Djurgarden
* EurobonusMastercard
* EurobonusMastercardDk
* EurobonusMastercardNo
* Eurocard
* Opel
* Quintessentially
* SJPrio
* Saab
* Statoil
* Wallet
=> Remove banks that require BankId

app/build.gradle
This enables for example a CI server to compile and verify the application without knowing the signing key.
=> Only require keystore password for the assembleRelease task.

bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/swedbank/AbstractSwedbank.java
Sets transactions to empty list for Swedbank CreditCard if problem occurs during transaction fetching.
Fixes #381
=> Sets transactions to empty list for Swedbank CreditCard

config/ide/androidstudio/AndroidStyle.xml
Adds codestyle template for AndroidStudio.
Use the template:
1. Place `AndroidStyle.xml` in your Android Studio `/codestyles` directory (e.g., `%userprofile%\.AndroidStudio\config\codestyles`, or `~/Library/Preferences/AndroidStudio/codestyles/` on OS X)
2. Restart Android Studio.
3. Go to "File->Settings->Code Style", and under "Scheme" select "AndroidStyle" and click "Ok".
4. Right-click on the files that contain your contributions and select "Reformat Code", check "Optimize imports", and select "Run".
=> Adds Android codestyle template for AndroidStudio.

config/quality/checkstyle/checkstyle.xml
Disabled checks: 
* MethodLength 
* EmptyBlock
* MagicNumber
* MissingSwitchDefaults
Added `content://` to ignorePattern for LineLength
=> Tuning checkstyle.

bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/AmericanExpress.java
It appears Marshmallow (at least) does not support the way the parser
was initialized anymore.
=> Fix Amex date parsing

bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/AmericanExpress.java
Many (most?) of the Amex card titles parsed from the site end up
being very long, which makes the amount included in the notifications
end up outside the screen.
Replace "American Express" with "Amex" and "EuroBonus" with "EB" in
order to shorten these down, while keeping them unique and easy
to identify.
=> Shorten Amex card titles

CHANGELOG, bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankFactory.java
Espresso House does no longer support card details via the web-page. 
Perhaps it is possible to reverse engineer the app request to read enable support..
=> Removed support for EspressoHouse

CHANGELOG, bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/TestBank.java
The account changes its balance randomly every time you refresh it.
The purpose of the volatile account is to help me debug why the widget
doesn't update even though the app does. For that I want an account that
always changes its balance.
Also, before this change the Test Bank didn't have any accounts, since
the URL where it tries to get its data from isn't available any more.
With this change in place the Test Bank at least gets one account.
=> Add a Volatile account to the Test Bank

CHANGELOG, CONTRIBUTORS.txt, app/build.gradle, app/src/main/java/com/liato/bankdroid/appwidget/AutoRefreshService.java, app/src/test/java/com/liato/bankdroid/appwidget/DataRetrieverTaskTest.java
Before this change:
* when the banks were auto updated
* and the bank's balance change was lower than the notification
threshold
... then the widget wasn't updated.
With this change in place the widget is actually updated even in this
case.
This change also adds unit testing of the auto update data retrieval
code.
=> Fix widget not refreshing on auto updates

CHANGELOG, app/src/main/java/com/liato/bankdroid/DataRetrieverTask.java, app/src/test/java/com/liato/bankdroid/DataRetrieverTaskTest.java
If the user refreshes an individual bank, we'll do it even if it's
disabled. The idea is that maybe it works this time around, and if
so we'll just be re-enable it.
Before this change, trying to refresh a disabled bank just silently did nothing.
This is one part of resolving #610.
=> Enable refreshing disabled banks

config/quality/quality.gradle
Before this change, just doing `./gradlew check` would fail because
FindBugs required `assembleDebug` to run first.
This change tells Gradle about this dependency and enables one to do
`./gradlew check` without doing `assembleDebug` first.
=> Fix "./gradlew check" task dependencies

app/src/main/java/com/liato/bankdroid/LockableActivity.java, app/src/main/java/com/liato/bankdroid/LockablePreferenceActivity.java, app/src/main/java/com/liato/bankdroid/PairApplicationsActivity.java, app/src/main/java/com/liato/bankdroid/adapters/AccountsAdapter.java, app/src/main/java/com/liato/bankdroid/appwidget/AutoRefreshService.java, app/src/main/java/com/liato/bankdroid/appwidget/BankdroidWidgetProvider.java, app/src/main/java/com/liato/bankdroid/appwidget/WidgetConfigureActivity.java, app/src/main/java/com/liato/bankdroid/db/DBAdapter.java, app/src/main/java/com/liato/bankdroid/lockpattern/LockPatternUtils.java, app/src/main/res/layout/widget.xml, app/src/main/res/layout/widget_large.xml, app/src/main/res/layout/widget_large_transparent.xml, app/src/main/res/layout/widget_transparent.xml, bankdroid-legacy/src/main/java/com/liato/bankdroid/Helpers.java, config/quality/lint/lint.xml, config/quality/pmd/pmd-ruleset.xml
Part of fixing #610.
On my phone, the account-disabled warning symbol in the widget is a bit outside of the widget and almost invisible.
Strikethrough is fine though, so this change replaces the warning icon in the widget with overstriking the balance if updates have been disabled for the account.
Also, in accordance with the Boy Scout Rule, this change fixes some warnings in `BankdroidWidgetProvider.java` and re-enables one Lint rule and one PMD rule.
=> Widget: Replace warning symbol with strikethrough

bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/americanexpress/model/AccountActivity.java
Make sure that transaction model for amex never return null, but an empty list if no transactions are available.
Fixes #637
=> Fixes Amex crashes

app/src/main/res/layout/transactions.xml, config/quality/pmd/pmd-ruleset.xml, tools/update-suppressions.sh
Also, boy-scout-principle update suppressions script to disable a PMD
rule that needs configuration to work that we don't supply right now.
=> Fix overlapping layout

CHANGELOG, app/src/main/java/com/liato/bankdroid/BankEditActivity.java, app/src/main/java/com/liato/bankdroid/DataRetrieverTask.java, app/src/main/java/com/liato/bankdroid/LockableActivity.java, app/src/main/java/com/liato/bankdroid/SettingsActivity.java, app/src/main/java/com/liato/bankdroid/StartupReceiver.java, app/src/main/java/com/liato/bankdroid/TransactionsActivity.java, app/src/main/java/com/liato/bankdroid/WebViewActivity.java, app/src/main/java/com/liato/bankdroid/appwidget/AutoRefreshService.java, app/src/main/java/com/liato/bankdroid/appwidget/WidgetConfigureActivity.java, app/src/main/java/com/liato/bankdroid/lockpattern/ChooseLockPattern.java, app/src/main/java/com/liato/bankdroid/provider/BankTransactionsProvider.java, app/src/main/res/layout/bank.xml, app/src/main/res/layout/pair_applications_layout.xml, app/src/main/res/layout/transactions.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml, bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/Account.java, bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/ica/model/Account.java, bankdroid-legacy/src/main/java/eu/nullbyte/android/urllib/CertPinningSSLSocketFactory.java, config/quality/lint/lint.xml, config/quality/pmd/pmd-ruleset.xml, config/quality/quality.gradle
If a bank is disabled, and you click on the widget, with this change in
place you now get a warning about the bank being disabled and what you
can do about it.
This is part of fixing #610.
To be able to work on this I first fixed all warnings in the two files
I had to change. To remove the suppressions for those warnings so that
they don't come back, I fixed all other instances of those problems as
well.
Note that this change also enables *all* Android Lint warnings (rather than just the on-by-default ones) before we disable those that we violate. That made some additional suppressions show up in `lint.xml`.
=> Add bank-disabled warning to TransactionsActivity

bankdroid-legacy/build.gradle, bankdroid-legacy/src/main/java/com/liato/bankdroid/utils/ExceptionUtils.java, bankdroid-legacy/src/main/java/eu/nullbyte/android/urllib/Urllib.java, bankdroid-legacy/src/test/java/com/liato/bankdroid/utils/ExceptionUtilsTest.java
In Crashlytics we have a lot of stack traces originating in Urllib.
With this change in place, those exceptions will appear to be
originating from whatever bank tried to call Urllib, and it will be
much more obvious in Crashlytics which banks actually have the most
problems.
=> Fake Urllib exception stack traces

app/src/main/java/com/liato/bankdroid/banking/BankFactory.java, app/src/main/java/com/liato/bankdroid/db/DBAdapter.java, app/src/main/java/com/liato/bankdroid/db/Database.java, app/src/main/java/com/liato/bankdroid/utils/LoggingUtils.java, app/src/main/java/net/sf/andhsli/hotspotlogin/SimpleCrypto.java, config/quality/lint/lint.xml
This is a step towards removing password encryption alltogether.
The background is that password encryption is broken on Android Nougat anyway, and that it
didn't provide any extra security before that either.
Since Bankdroid needs to send plain text passwords to the banks, it must
be possible to retrieve the plain text passwords automatically. And if
the passwords are encrypted on disk, Bankdroid needs to have the key.
And if Bankdroid stores both the key and the encrypted password on the
phone, a determined attacker could get both anyway, and the encryption
is useless.
The only thing the encryption has protected against is a user rooting
their own device and retrieving their own plain text passwords. This
would enable the attacker to read their own account balance from the
bank.
Which …
=> Ensure on-disk passwords are unencrypted

app/src/main/java/com/liato/bankdroid/DataRetrieverTask.java, app/src/main/java/com/liato/bankdroid/appwidget/AutoRefreshService.java, app/src/main/java/com/liato/bankdroid/utils/LoggingUtils.java
With this change in place we'll be able to see in Crashlytics:
* which banks are most frequently disabled
* which banks are most frequently used
* for which banks transactions updating doesn't work
=> Log bank usage statistics to Crashlytics

CHANGELOG, bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/Ostgotatrafiken.java
Östgötatrafiken now supports three ways to log in/authenticate:
- An e-mail address
- A username (for legacy users (such as me))
- Facebook login
Bankdroid only supports e-mail/username login.
(I haven't tested e-mail login, but I expect it to work the same way
as for username logins)
---
You may want to add Östgötatrafiken to the list of supported "banks" on the play store.
=> Östgötatrafiken: Adapt to new login page

bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyBankFactory.java
So instead of getting in Crashlytics...
BankType id not found.
... we now get...
BankType id not found: 1234
This way it will be easier to understand why we get these exceptions and
how they should be handled (or not).
=> If asked for an unknown bank, log the id

bankdroid-legacy/src/main/java/com/liato/bankdroid/utils/ExceptionUtils.java, bankdroid-legacy/src/test/java/com/liato/bankdroid/utils/ExceptionUtilsTest.java, bankdroid-legacy/src/test/java/not/bankdroid/at/all/ExceptionThrower.java
Before this change, bankdroidifyException() failed if the exception
to wrap didn't come with a String constructor.
Now it works, with tests and all!
=> Fix wrapping exceptions without String constructors

bankdroid-legacy/src/main/java/com/liato/bankdroid/utils/ExceptionUtils.java, bankdroid-legacy/src/main/java/eu/nullbyte/android/urllib/Urllib.java, bankdroid-legacy/src/test/java/com/liato/bankdroid/utils/ExceptionUtilsTest.java, bankdroid-legacy/src/test/java/not/bankdroid/at/all/ExceptionFactory.java, config/quality/lint/lint.xml, tools/update-suppressions.sh
For Crashlytics.
The previous attempt at doing this failed, because it tried to modify
the *first* exception in the chain, but it turns out that it's the
*last* exception in the chain that Crashlytics looks at.
So given an Exception...
"
java.lang.Exception: This is a test Exception
at not.bankdroid.at.all.ExceptionFactory.getException(ExceptionFactory.java:20)
at com.liato.bankdroid.utils.ExceptionUtilsTest.testBlameBankdroid(ExceptionUtilsTest.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at ...
"
... we now report to Crashlytics:
" …
=> Blame Urllib problems on the callers

bankdroid-legacy/src/main/res/values-sv/strings.xml, bankdroid-legacy/src/main/res/values/strings.xml, config/quality/lint/lint.xml
Before Android Studio 2.3.0 having these enabled triggered internal errors in Lint. Those errors have now been fixed and the checks can be re-enabled.
=> Re-enable some Unused warnings
